name: installments_payments
filename: installments_payments.csv
primary_key: null
row_count_reference: 13605401
row_count_tolerance: 0.02
columns:
- name: SK_ID_PREV
  dtype: int64
  nullable: false
  null_rate_reference: 0.0
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: 1000001.0
  max_value: 2843499.0
- name: SK_ID_CURR
  dtype: int64
  nullable: false
  null_rate_reference: 0.0
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: 100001.0
  max_value: 456255.0
- name: NUM_INSTALMENT_VERSION
  dtype: float64
  nullable: false
  null_rate_reference: 0.0
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: 0.0
  max_value: 178.0
- name: NUM_INSTALMENT_NUMBER
  dtype: int64
  nullable: false
  null_rate_reference: 0.0
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: 1.0
  max_value: 277.0
- name: DAYS_INSTALMENT
  dtype: float64
  nullable: false
  null_rate_reference: 0.0
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: -2922.0
  max_value: -1.0
- name: DAYS_ENTRY_PAYMENT
  dtype: float64
  nullable: true
  null_rate_reference: 0.000214
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: -4921.0
  max_value: -1.0
- name: AMT_INSTALMENT
  dtype: float64
  nullable: false
  null_rate_reference: 0.0
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: 0.0
  max_value: 3771487.845
- name: AMT_PAYMENT
  dtype: float64
  nullable: true
  null_rate_reference: 0.000214
  null_rate_tolerance: 0.02
  is_unique: false
  allowed_values: null
  min_value: 0.0
  max_value: 3771487.845
